name: Docker Build and Release
on: [ push , workflow_dispatch]
env:
#### An dieser Stelle müssen eure persönlichen Umgebungsvariablen eingetragen werden
  # Tip: Die Token/der API-Key werden als Secrets in den Repository-Settings eingetragen und hier referenziert.
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
        cache: maven
    #### AUFGABE 2: SONAR
      # hier ist der Platz für die Konfiguration der Sonar Analyse
  
    - name: Compile, build and push
      run: |
        mvn package  # Fügt den Maven-Package-Befehl hinzu
        docker build --tag mxcxvm/pet-clinic:latest -f Dockerfile  # Fügt den Docker-Build-Befehl hinzu
        #### AUFGABE 3 COMPILE, DOCKER BUILD UND PUSH
          # hier ist Platz für maven package und docker build
          
